### PR TITLE
Replaced NodeJs specific Buffer API GH-5

### PR DESCRIPTION
**Pull request by mrbrianevans**
Replaced usage of `Buffer.from` with custom base64toBuffer function written by @sanjayaksaxena in GH-5.

This enables the module to be used in web browsers without transformation using a tool like browserify. 

I have tested the change by putting the code in `node_modules` of a project which uses the english model. Before the change, there is an error message in the browser console:
```
Uncaught ReferenceError: Buffer is not defined
    at readModel (read-core-model.js:1:260)
    at Object.loadModel [as core] (load-core-model.js:1:78)
    at load (wink-nlp.js:137:22)
    at nlp (wink-nlp.js:408:3)
```
After the change, it functions as expected with no error messages.

### CODE REVIEW

**Comment by mrbrianevans** [comment]
Fixes #5

**Review by sanjayaksaxena — COMMENTED** [review]
A specific conversion: `model.lexicon = new Uint32Array( lexiconAsBuffer.buffer, 0, ( lexiconAsBuffer.length / 4 ) );` and `model.xpansions = new Uint32Array( xpansionsAsBuffer.buffer, 0, ( xpansionsAsBuffer.length / 4 ) );` would be necessary as internally it assumes data to be available in **Uint32Array** format.

Has it worked with winkNLP properly?

**Comment by mrbrianevans** [comment]
Sorry an oversight on my part. I only tested the "hello world" example and
it worked as expected, but should probably test the POS tagging or
something to confirm that the language model lexicon has loaded correctly.

**Comment by sanjayaksaxena** [comment]
Would recommend to incorporate the change and then test as internally it assumes Uint32Array.

**Comment by mrbrianevans** [comment]
Okay, I have done the conversion from ArrayBuffer to Uint32Array, and tested it and its working as expected. It can correctly tag parts of speech, so the lexicon must be working.

As an example, this is the output with the changes implemented:
```
token      p-spaces   prefix  suffix  shape   case    nerHint type     normal/pos 
——————————————————————————————————————————————————————————————————————————————————————— 
  “                 0   “       “       “       0       0       punctuat “ / PUNCT 
  He                0   He      He      Xx      3       0       word     he / PRON 
  is                1   is      is      xx      1       0       word     is / AUX 
  just              1   ju      ust     xxxx    1       0       word     just / ADV 
  what              1   wh      hat     xxxx    1       0       word     what / PRON 
  a                 1   a       a       x       1       0       word     a / DET 
  young             1   yo      ung     xxxx    1       0       word     young / ADJ 
  man               1   ma      man     xxx     1       0       word     man / NOUN 
  ought             1   ou      ght     xxxx    1       0       word     ought / AUX 
  to                1   to      to      xx      1       39      word     to / PART 
  be                1   be      be      xx      1       0       word     be / AUX 
  ,                 0   ,       ,       ,       0       0       punctuat , / PUNCT 
  ”                 0   ”       ”       ”       0       0       punctuat ” / PUNCT 
```

The rightmost column shows it correctly identified English words POS.

I have also added JSDoc on the function to make it clearer what type it returns.

Is this change a minor or patch version bump?

**Review by sanjayaksaxena — APPROVED** [review]
Looks good :-)

**Comment by sanjayaksaxena** [comment]
It is more like a patch unless you have another view?

**Comment by mrbrianevans** [comment]
No, patch seems good to me.

**Pull request merged**
